WITH DF AS (

select INTERVAL_DATETIME, REGIONID, OPERATIONAL_DEMAND, LASTCHANGED, MONTH(INTERVAL_DATETIME) as "MONTH"
FROM  mms.demandoperationalactual

),
TOPTEN AS (
select INTERVAL_DATETIME, MONTH, REGIONID, OPERATIONAL_DEMAND, LASTCHANGED, ROW_NUMBER()
OVER (
  PARTITION BY REGIONID, MONTH
  ORDER BY OPERATIONAL_DEMAND
) as RowNo
from DF
),
BOTTEN AS (
select INTERVAL_DATETIME, MONTH, REGIONID, OPERATIONAL_DEMAND, LASTCHANGED, ROW_NUMBER()
OVER (
  PARTITION BY REGIONID, MONTH
  ORDER BY OPERATIONAL_DEMAND DESC
) as RowNo
from DF
)

SELECT * FROM TOPTEN WHERE RowNo = 1
UNION
SELECT * FROM BOTTEN WHERE RowNo = 1
